### ISSUE TITLE
petridish server should fallback to README.md if index.md is not found

### ISSUE THREAD

**Issue by tripodsan** [adobe/petridish#12]
should it ?

**Comment by trieloff** [comment]
I don't want too much magic in the production pipeline, but we could adjust the start URL based on the presence of readme.md and index.md

**Comment by tripodsan** [comment]
Actually, I'd prefer to have `index.md` for the default _directory rendering_ fallback. and I would reserve the README.md for the description of the project.

I think it is very likely, that content owners want to keep this separate; i.e. show on github how the content repository is to be used, and don't want to show this on the homepage.

@davidnuescheler wdyt?

**Comment by kptdobe** [comment]
While I agree the `README.md` might serve a different purpose (repo description) in git, assuming an `index.md` will be a pain because people will forget, especially that github navigation falls back to `README.md` (just try https://github.com/Adobe-Marketing-Cloud/reactor-user-docs/tree/master/getting-started).

As a real life example, the helpx team did use the README.md files as an index and other files to describe some "purpose" (like https://github.com/Adobe-Marketing-Cloud/reactor-user-docs/blob/master/CODE_OF_CONDUCT.md)

**Comment by trieloff** [comment]
I think we will need an `index` setting sooner or later. The advantage of `index.md` is that it is clean, analogous to how `index.html` works.

The advantage of `README.md` is that this is exactly how GitHub does it, with `README.md` being added to every directory.

So my solution would be this:
- the default for `index` is `index.md`
- you can override it with an `index` setting in your Strain Configuration
- when petridish starts, it suggests a URL to open. If no settings are present, it will try:
  1. `index.md`
  2. `README.md`
  3. `*.md` so that starting `hlx` in an empty project with just a random `md` file will give you a reasonable result

**Comment by tripodsan** [comment]
I think _iii_ is not good because it is even less deterministic.
the problem with the fallback is, that it needs a 2nd request. so we'd rather have it configurable with no fallback

**Comment by trieloff** [comment]
I would not implement it as a fallback in the rendering pipeline, but rather in the (CLI) user interface. When we generate the message `open http://localhost:<port>/<file>.html` we populate `<file>` with whatever the algorithm comes up with.

If you go to `http://localhost:<port>/`, it will use the deterministic index resource.

**Comment by tripodsan** [comment]
closing as wont-fix.
